language: php
 
php:
     - hhvm
 
install:
   - composer self-update
   - composer install
script:
     - phpunit --coverage-clover build/logs/clover.xml -c tests/phpunit.xml
 
after_script:
     - php vendor/bin/coveralls
 
notifications:
     email: false

