#language: node_js
#node_js:
 # - node
#install: npm install
#script: npm test
#notifications:
 # email:
  #  recipients:
   #   - nadine.jakob@hs-furtwangen.de
    #  - florian.moehrle@hs-furtwangen.de
    #on_success: always
    #on_failure: always

language: php
php:
- '7'
notifications:
 email:
   recipients:
    - nadine.jakob@hs-furtwangen.de
    - florian.moehrle@hs-furtwangen.de
    on_success: always
    on_failure: always
