language: node_js
node_js:
  - "node"
install: npm install
notifications:
  email:
    recipients:
      - nadine.jakob@hs-furtwangen.de
      - florian.moehrle@hs-furtwangen.de
    on_success: always
    on_failure: always
